export const stateList = [ 'AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MH', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP', 'OH', 'OK', 'OR', 'PW', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY' ];

export const fields = ['date',
    'death',
    'deathIncrease',
    'hospitalized',
    'hospitalizedCumulative',
    'hospitalizedCurrently',
    'hospitalizedIncrease',
    'inIcuCumulative',
    'inIcuCurrently',
    'negative',
    'negativeIncrease',
    'onVentilatorCurrently',
    'positive',
    'positiveIncrease',
    'recovered'
    ]

export const countryList = [
 "Uruguay",
  "Bangladesh",
  "Sweden",
  "Peru",
  "Kenya",
  "Czech Republic",
  "China",
  "Thailand",
  "Viet Nam",
  "Canada",
  "Ireland",
  "United States of America",
  "Israel",
  "Brazil",
  "Finland",
  "Croatia",
  "Portugal",
  "Philippines",
  "Singapore",
  "Indonesia",
  "Argentina",
  "Japan",
  "Korea (South)",
  "Turkey",
  "Italy",
]